/*
 * Licensed to the Indoqa Software Design und Beratung GmbH (Indoqa) under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Indoqa licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.indoqa.boot.html.react;

/**
 * Utility methods to find Javascript and CSS assets generated by Webpack.
 */
final class WebpackAssetsUtils {

    private static final String ASSETS_PATH = "assets";
    
    private WebpackAssetsUtils() {
        // hide utility class constructor
    }

    static String getAssetsFolder(String folder, String mountPath) {
        StringBuilder builder = new StringBuilder();

        builder.append(removeTrailingSlash(folder));

        if (!mountPath.startsWith("/")) {
            builder.append("/");
        }

        builder.append(removeTrailingSlash(mountPath));

        if (builder.charAt(builder.length() - 1) != '/') {
            builder.append("/");
        }

        builder.append(ASSETS_PATH);

        return builder.toString();
    }

    private static String removeTrailingSlash(String path) {
        return path.replaceAll("/$", "");
    }
}
